// This file was generated by lezer-generator. You probably shouldn't edit it.
export const EnvEndCommand = 1;

export const MismatchedEnvEndCommand = 2;

export const VerbatimContent = 3;

export const VerbContent = 4;

export const ControlWord = 6;

export const ControlSpace = 7;

export const ControlLine = 8;

export const ControlSymbol = 9;

export const ControlSequenceName = 10;

export const CommandName = 85;

export const Environment = 15;

export const GenericEnvironment = 16;

export const BeginEnvironment = 25;

export const EnvironmentName = 29;

export const EnvironmentOption = 27;

export const EndEnvironment = 28;

export const VerbatimEnvironment = 24;

export const Argument = 83;

export const VerbCommand = 84;

export const VerbLeftDelim = 86;

export const VerbRightDelim = 87;

export const ReservedCharacter = 88;

export const Parameter = 89;

export const Comment = 90;

export const MathBlock = 91;

export const MathContent = 96;

export const MathLine = 94;
